const clickhouseTypes = [
    'AggregateFunction',
    'Array',
    'Bool',
    'Date',
    'Date32',
    'DateTime',
    'DateTime32',
    'DateTime64',
    'Decimal',
    'Decimal128',
    'Decimal256',
    'Decimal32',
    'Decimal64',
    'Dynamic',
    'Enum',
    'Enum16',
    'Enum8',
    'FixedString',
    'Float32',
    'Float64',
    'IPv4',
    'IPv6',
    'Int128',
    'Int16',
    'Int256',
    'Int32',
    'Int64',
    'Int8',
    'IntervalDay',
    'IntervalHour',
    'IntervalMicrosecond',
    'IntervalMillisecond',
    'IntervalMinute',
    'IntervalMonth',
    'IntervalNanosecond',
    'IntervalQuarter',
    'IntervalSecond',
    'IntervalWeek',
    'IntervalYear',
    'JSON',
    'LineString',
    'LowCardinality',
    'Map',
    'MultiPolygon',
    'Nested',
    'Nothing',
    'Nullable',
    'Object',
    'Point',
    'Polygon',
    'Ring',
    'SimpleAggregateFunction',
    'String',
    'Tuple',
    'UInt128',
    'UInt16',
    'UInt256',
    'UInt32',
    'UInt64',
    'UInt8',
    'UUID',
    'Variant',
    'BIGINT',
    'BIGINT SIGNED',
    'BIGINT UNSIGNED',
    'BINARY',
    'BINARY LARGE OBJECT',
    'BINARY VARYING',
    'BIT',
    'BLOB',
    'BYTE',
    'BYTEA',
    'CHAR',
    'CHAR LARGE OBJECT',
    'CHAR VARYING',
    'CHARACTER',
    'CHARACTER LARGE OBJECT',
    'CHARACTER VARYING',
    'CLOB',
    'DEC',
    'DOUBLE',
    'DOUBLE PRECISION',
    'ENUM',
    'FIXED',
    'FLOAT',
    'GEOMETRY',
    'INET4',
    'INET6',
    'INT',
    'INT SIGNED',
    'INT UNSIGNED',
    'INT1',
    'INT1 SIGNED',
    'INT1 UNSIGNED',
    'INTEGER',
    'INTEGER SIGNED',
    'INTEGER UNSIGNED',
    'LONGBLOB',
    'LONGTEXT',
    'MEDIUMBLOB',
    'MEDIUMINT',
    'MEDIUMINT SIGNED',
    'MEDIUMINT UNSIGNED',
    'MEDIUMTEXT',
    'NATIONAL CHAR',
    'NATIONAL CHAR VARYING',
    'NATIONAL CHARACTER',
    'NATIONAL CHARACTER LARGE OBJECT',
    'NATIONAL CHARACTER VARYING',
    'NCHAR',
    'NCHAR LARGE OBJECT',
    'NCHAR VARYING',
    'NUMERIC',
    'NVARCHAR',
    'REAL',
    'SET',
    'SIGNED',
    'SINGLE',
    'SMALLINT',
    'SMALLINT SIGNED',
    'SMALLINT UNSIGNED',
    'TEXT',
    'TIME',
    'TIMESTAMP',
    'TINYBLOB',
    'TINYINT',
    'TINYINT SIGNED',
    'TINYINT UNSIGNED',
    'TINYTEXT',
    'UNSIGNED',
    'VARBINARY',
    'VARCHAR',
    'VARCHAR2',
    'YEAR',
    'bool',
    'boolean',
]

const starrocksTypes = [
    'BIGINT',
    'BIT',
    'BLOB',
    'BOOLEAN',
    'CHAR',
    'DATE',
    'DATETIME',
    'DECIMAL',
    'DOUBLE',
    'FLOAT',
    'INT',
    'LARGEINT',
    'SMALLINT',
    'STRING',
    'TEXT',
    'TIME',
    'TINYINT',
    'VARCHAR',
]

const dockerTypes = ['datetime', 'string']
const kubernetesTypes = ['datetime', 'string']

const FieldTypes = {
    clickhouse: clickhouseTypes,
    starrocks: starrocksTypes,
    docker: dockerTypes,
    kubernetes: kubernetesTypes,
}

export { FieldTypes }
